version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  style_guide = "google"
  plugins = [
    "meteor",
    "react",
    "vue"
  ]
  environment = ["jest"]
